server:
  port: 8082

spring:
  application:
    name: User-Service
  config:
    import: optional:configserver://localhost:8086
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: pawan123
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
#  zipkin:
#    base-url: http://localhost:9411/zipkin/
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
      
management:
  health:
    circuitbreakers:
      enabled: true
  
  endpoints:
    web:
      exposure:
        include: health
        
  endpoint:
    health:
      show-details: always
      
resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 6s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: count-based
 